### PR TITLE
hackish support for reading laz files 

### PR DESCRIPTION
**Pull request by silyko**
Inspired by slash by Thomas Knudsen, http://bitbucket.org/busstop/helios . We currently use that for reading laz-files in our LIDAR QC-code: http://bitbucket.org/GSTudvikler/gstdhmqc

Implements basic support for reading laz-files via a call to laszip and a buffer object. Currently numpy does not seem to be able to create arrays from memoryviews, so both buffer and memoryview used in FakeMmap. Had to disable populate_evlrs for this hack, due to a KeyError in the header_format.lookup -mapping. Tested to work on win7 from Osgeo4W64. Only read-mode implemented...

### CODE REVIEW

**Comment by silyko** [comment]
Tried to integrate reading laz files better. If a compressed format is detected in File.open, a buffer object will be constructed (when read_compressed is True (default)).
This means that you can just do lasfile = file.File("somefile.laz").. Seems to work for me :)

**Comment by grantbrown** [comment]
Thanks for the help. I've refactored your work a bit after merging, starting with [72d5c](https://github.com/grantbrown/laspy/commit/72d5c96af1bd852ac7ba30d870421d3b5f825374). I tried to simplify the required arguments (no need for manual specification of whether a file is compressed or not), and tried to fit the buffer approach into existing fields (mmap, rather than additional buf_obj). 

Thanks again,
-Grant

**Comment by silyko** [comment]
Great! Nice to get this working and integrated better. I noticed a minor issue when reading a more complex laz-file. 
Final part of traceback:

/home/sik/dvl/laspy/laspy/base.pyc in get_header_property(self, name)
    679             return(self.header_properties[name])
    680         else:
--> 681             spec = self.header_format.lookup[name]
    682             val = self._get_datum(0, spec)
    683             self.header_properties[name] = val

KeyError: 'start_wavefm_data_rec'

Haven't looked much into it, but remember that I earlier just disabled the call:

--> 284             self.populate_evlrs(),

I can make an example laz file avaible if you need it?

**Comment by grantbrown** [comment]
Definitely, laz files with EVLRs aren't currently covered by the test suite.

**Comment by silyko** [comment]
The problem with the file in question, is:
In [9]: f.reader.grab_file_version()
Out[9]: '1.1'
In [10]: f.reader.header.version
Out[10]: '1.3'

This means that the code in util.py (line 243):
 if fmt in ("h1.3", "h1.4"):
            self.add("start_wavefm_data_rec", "ctypes.c_ulonglong", 1)
won't be called. So the header_format will have no key "start_wavefm_data_rec", and populate_evlrs will fail.

Not being an expert on the LAS format, I'm not able to say if this file has an invalid format or if this is something that should be supported. 
An example file can be found at:  https://dl.dropboxusercontent.com/u/97068354/test.laz
It is a small piece of a LAZ file downloaded from the Danish Geodata Agency: http://download.kortforsyningen.dk
Same issue with all other LAZ files available (for free) there.
.

**Comment by silyko** [comment]
Hmm - was a simple bug in FakeMemoryMap... will fix it...

**Comment by grantbrown** [comment]
Just got it: https://github.com/grantbrown/laspy/commit/de6d92a1ddfaa3066b79ffe07d83027a6325d483

**Pull request merged**
